import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import React from 'react';
import styles from '../styles/Home.module.css'

const API_URL = "/api/hello";

export default function Home() {
  const [data, setData] = React.useState(""); 

  const fetchData = async () => {
    const res = await fetch(API_URL);
    const resData = await res.json();
    const {name} = resData; 
    setData(name);
  }
  
  React.useEffect(() => {
    fetchData(); 
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title> My-App-2 </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://github.com/cscifresnostate"> the CSCI Club. </a>
        </h1>
        <h1 className={styles.title}>
          Go to <Link href="/api/hello"> API. </Link>
        </h1>
        <h1> 
          My name is: {data}
        </h1>
        <button onClick={() => fetchData()}> Click Me! </button>
          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
